// @version 4.0.577
(function(h,l,k,B,K,C,L,r,u,pa,T,z,v,M,ea,w,p,A,s,qa,U,V,D,fa,N,W,ga,E,m){var O,P,X;function F(a,b,c,d){var f;(f=a.addEventListener)?f.call(a,b,c,v):a.attachEvent(d||"on"+b,c)}function x(a,b){return function(){a(b)}}function ha(a){function b(a){return"expires="+(new L(a)).toGMTString()+";"}var c="path=/;",d=n("cookieDomain");d&&(c+="domain="+d+";");return{G:function(f,d){O&&(k[V]=f+"="+d+";"+b(+new L+(a?6E10:6E4))+c)},w:function(a){if(O)return(k[V].match("(^|;)\\s*"+a+"=(.*?)(;|$)")||[])[2]||M},ba:function(a){k[V]=
a+"=;"+b(0)+c}}}function G(a){function b(){var a=f[D];a&&(f[D]=a[p](c)[0])}var c=":_GS_:",d;if(G.I)return G.I;var f=l.top;G.I=d={t:function(){b();f[D]=(f[D]||"")+c+[a,d.n,d.k]}};try{var g=f[D]||"";if(-1!=g[E](c)){var j=g[p](c)[1][p](",");j[0]==a&&(d.n=j[1]||"",d.k=j[2]||"")}b()}catch(i){d.t=function(){}}return d}function Y(a){var b,c,d,f;b=/[?&]([^=]+)=([^&]*)/g;c={};for(f=pa;d=b.exec(a[A](/\+/g," "));c[f(d[1])]=f(d[2]));return c}function n(a,b){a=h[a];return a!==m?a:b}function ra(a,b){var c,d=l._gstc_lt,
f=Q(Q(a).P),g=f.xa+(n("trackParams",z)?f.R:"")[A](/[?&]utm_[^=]*=[^&]*/g,"")+(n("trackHash")?f.wa:""),j=b!==m?b:k.title,i=f.O,e=f.Q,o=f.ya;c=(c=l._gstc_s)&&d?d-c:m;var H;d&&(H=new L-d-n("TrackDelay"));return{ka:g,ua:j,ca:i,oa:e,qa:o,ma:c,va:H,fa:"file:"==f.Q,ea:/fb_xd_(bust|fragment)/.test(f.P)}}function sa(){var a=n("referrer",k.referrer),b=k.domain,c=v,d=Q(a).O;!a||/^(chrome|about|file):$/.test(a)?a="-":(b=d[E](b),c=0<=b&&8>=b,a=/^\[.*\]$/.test(a)?"-":a);var f,g={z:+c,sa:a};if("-"!=a)for(y=0;y<
Z[s];)if(b=Z[y++],-1<d[E](b.d)){c=Y(a);if("google"==b.d&&(/images\.google/.test(d)||/\/imgres/.test(a)))if(c.prev&&(f=Y(c.prev).q))g.h={d:"googlei",C:f};c[b.B]&&(g.h={d:b.d,C:c[b.B]})}return g}function ta(a){var a=Q(a).R,b=Y(a),c;if(a&&(c=b.utm_campaign))return{X:c,Y:b.utm_source,W:b.utm_medium,Z:b.utm_term,V:b.utm_content}}function ua(a,b,c){var d=ha(1),f=G(a.c),g=d.w("gs_u")||f.n,j=1,i=1,e=(g||"")[p](":"),o,H=z,k=0,$;!g||!g.match(/^[0-9\:]*$/)?(H=v,g=0|C.random()*ea):(g=e[0],2>e[s]&&(e[1]=2019,
e[2]=4621),4>e[s]&&(e[3]=0),j=(e[1]-2019)/548+ +!!b,i=(e[2]-4621)/379+1,k=e[3]/1E3);d.G("gs_u",f.n=[g,2019+548*j,4621+379*i,+new L].join(":"));b=d.w(P+a.c)||f.k;b!==M&&b!==m&&($=b,d.ba(P+a.c));c&&($=a.id);if((a=n("Visitor"))&&"object"==typeof a){o=[];for(var h in a)a[fa](h)&&o.push(h+"="+("gravatar"==h?va(a[h][A](/^\s+|\s+$/g,"")[U]()):a[h]));o=o.join("|")}return{id:+g,za:j,ra:i,ia:~~k,ta:H,na:$,aa:o}}function aa(a){var b=["data.gosquared.com/"],c=k[ga]("head")[0],d=k[w]("script"),f=v,g=r(function(){c[N](d);
d=M;ba=(ba+1)%b[s];aa(a)},1E4),j=a.F+"?"+function(a){var c=[],b;for(b in a)a[fa](b)&&a[b]!==m&&c.push((T||escape)(b)+"="+(T||escape)(a[b]));return c.join("&")}(a.D);d.src="//"+b[ba]+j;d.onload=d.onreadystatechange=function(b){b=this.readyState;if(!f&&(!b||"loaded"==b||"complete"==b))f=z,a.m&&a.m(),c[N](d),d=M,u(g)};c[W](d)}function wa(){function a(a){for(var a=[a[A](/^./,function(a){return a[U]()}),"Webkit"+a,"Moz"+a,"O"+a,"ms"+a],c=a[s];c--;)if(d[a[c]]!==m)return 1}var b="a"+(0|C.random()*ea),c=
k[w]("div"),d=c.style,f=k[w]("canvas"),g,j=0;try{localStorage.set(b,b),localStorage.remove(b),j=1}catch(i){}var e=!!a("Perspective");if(e&&"webkitPerspective"in d){var o=k[w]("style");o.textContent="@media (-webkit-transform-3d){#"+b+"{height:3px}}";k[ga]("head")[0][W](o);c.id=b;k.body[W](c);e=3==c.offsetHeight;o.parentNode[N](o);c.parentNode[N](c)}return[+!(!f.getContext||!f.getContext("2d")),+!!l.WebGLRenderingContext,+("geolocation"in B),+!(!(g=l.history)||!g.pushState),+("WebSocket"in l||"MozWebSocket"in
l),+!!k[w]("video").canPlayType,+!!k[w]("audio").canPlayType,+("placeholder"in k[w]("input")),+j,+!!a("Transform"),+e,+!!a("Transition"),+function(a,c){var b=c+a+"-";d.cssText=a+b+["webkit","moz","ms","o-"].join("-"+b)+c;return-1<d.background[E]("gradient")}("background:","linear-gradient(top,red,red);"),+!!a("AnimationName"),+!!l.Worker].join("")}function ia(){function a(a){return l["inner"+a]||d&&d[f="client"+a]||c&&c[f]}function b(a){return C.max(c[f="scroll"+a],d[f],c[f="offset"+a],d[f],c[f="client"+
a],d[f])}var c=k.body,d=k.documentElement,f;return{U:a("Width"),S:a("Height"),v:b("Width"),s:b("Height"),J:l.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft||0,K:l.pageYOffset||c&&c.scrollTop||d&&d.scrollTop||0}}function xa(){var a={b:{g:0,f:0},p:"-",ha:(B.language||B.browserLanguage||"-")[U](),ga:+B.javaEnabled(),$:k.characterSet||k.Ba||"-",da:function(a,b){var f,g,j,i,e;if(B&&(f=B.plugins)&&0<(g=f[s]))for(e=0;e<g;e++){if(-1<(i=f[e])[D][E](j=a+" "+b))return i.description[p](j+" "),i.description[p](j+
" ")[1]}else if(f=l.ActiveXObject){try{if(i=(new f((j=a+b+".")+a+b)).GetVariable("$version"))return i=i[p](" ")[1][p](","),i[0]+"."+i[1]+" r"+i[2]}catch(k){}for(e=13;--e;)try{if(i=new f(j+j+e),self.Ca=i&&i.Aa,i)return e+".0"}catch(h){}}return"-"}("Shockwave","Flash")};if(K)a.b={g:K.width,f:K.height},a.p=K.colorDepth;else if(l.java)try{I=java.awt.Toolkit.getDefaultToolkit(),y=I.getScreenSize(),a.b={g:y.width,f:y.height}}catch(b){}return a}function ja(a){a.j=z;u(a.L)}function ca(a){a.j=v;a.L=r(x(ya,
a),36E6)}function ya(a){a.M=z;u(a.L)}function ka(a){a.j||(ja(a),u(a.o),a.o=r(x(ca,a),6E4))}function la(a,b){a[b.shift()].apply(a,b)}function R(a,b,c){if(!a.ja&&!a.M)if(a.id!==m){b!==m||(b=a.j?"focus":"blur");if(c===m)var d=ia(),c={vw:d.U,vh:d.S,dw:d.v,dh:d.s,st:d.K,sl:d.J};c=c||{};c.a=a.c;c.u=a.uid;c.i=a.id;c.e=b;c._=C.random();da&&a.A&&t&&(a.A=v,c.o_si=t.H,c.o_vi=t.T,c.o_ci=t.r);aa({F:"ping",m:function(){if(h.ps){u(a.l);if(!a.M)a.l=r(x(R,a),2E4);delete h.ps}},D:c})}else{var f=arguments;r(function(){R.apply(this,
f)},5E3)}}function ma(a){this.c=a;this.j=v}function na(a,b){b||(b=X);return h[b]?(oa(b),h[b]):h[b]=new ma(a)}function oa(a){a||(a=X);h[a]&&u(h[a].N)}var Q=function(a){return function(b,c){b===m&&(b=location.href);a.href=b;return c={xa:a[qa][A](/^([^\/]|$)/,"/$1"),wa:a.hash[A](/^#$/,""),Q:a.protocol[A](/^:$/,"")||location.protocol,O:a.hostname||location.hostname,P:a.href,R:a.search,ya:a.port}}}(k[w]("a"));P="gs_p_";O=!n("noCookies");X="DefaultTracker";for(var va=function(a){function b(a,b){return((a>>
1)+(b>>1)<<1)+(a&1)+(b&1)}for(var c=[],d=0;64>d;)c[d]=0|4294967296*C.abs(C.sin(++d));return function(d){for(var g,j,i,e,k=[],d=unescape(T(d)),h=d[s],m=[g=1732584193,j=-271733879,~g,~j],l=0;l<=h;)k[l>>2]|=(d.charCodeAt(l)||128)<<8*(l++%4);k[d=(h+8>>6)*a+14]=8*h;for(l=0;l<d;l+=a){h=m;for(e=0;64>e;)h=[i=h[3],b(g=h[1],(i=b(b(h[0],[g&(j=h[2])|~g&i,i&g|~i&j,g^j^i,j^(g|~i)][h=e>>4]),b(c[e],k[[e,5*e+1,3*e+5,7*e][h]%a+l])))<<(h=[7,12,17,22,5,9,14,20,4,11,a,23,6,10,15,21][4*h+e++%4])|i>>>32-h),g,j];for(e=4;e;)m[--e]=
b(m[e],h[e])}for(d="";32>e;)d+=(m[e>>3]>>4*(1^e++&7)&15).toString(a);return d}}(16),q="google0yahoo2p0msn0bing0aol210aol2encquery0lycos210ask0altavista0netscape210cnn010looksmart2qt0about2terms0mamma210alltheweb0gigablast0voila2rdata0virgilio2qs0live0baidu2wd0alice2qs0yandex2text0najdi0aol0club-internet0mama210seznam0search0wp2szukaj0onet2qt0netsprint0google.interia0szukacz0yam2k0pchome"[p](0),Z=[],I,S,y=0;y<q[s];)I=q[y++][p](2),S=I[1],Z.push({d:I[0],B:S?1==S?"query":S:"q"});var ba=0,da=v,t,q=ma.prototype;
q.TrackView=function(a,b){var c=ra(a,b),d=sa(),f=ua(this,!d.z,a!==m),g=xa(),j=ta(a),i=ia();if(!(c.fa||c.ea||g.b.g&&g.b.f&&10>g.b.g&&10>g.b.f)){var e=this,c={a:e.c,cs:g.$,cd:g.p,fl:g.da,je:g.ga,la:g.ha,sw:g.b.g,sh:g.b.f,dm:c.ca,pa:c.ka,pt:c.ua,pr:c.oa,po:c.qa,pl:~~c.ma,tl:~~c.va,ri:d.z,ru:d.sa,ui:f.id,re:f.ta,vi:f.za,pv:f.ra,lv:f.ia,vw:i.U,vh:i.S,dw:i.v,dh:i.s,st:i.K,sl:i.J,tv:"4.0",un:n("UserName")||n("VisitorName"),pp:f.na,cp:f.aa,ec:n("errorCode"),bs:wa()};e.uid=f.id;a===m&&(c.id=e.id);d.h&&(c.oe=
d.h.d,c.ok=d.h.C);j&&(c.c_n=j.X,c.c_s=j.Y,c.c_m=j.W,c.c_c=j.V,c.c_t=j.Z);da&&(t?(c.o_si=t.H,c.o_vi=t.T,c.o_ci=t.r):e.A=z);d={F:"pv",D:c,m:function(){if(h.overLimit)e.ja=z;else if(h.id!==m){e.id=h.id;delete h.id;e.l=r(function(){R(e)},15E3);F(l,"beforeunload",function(){var a=ha();if(O)a.G(P+e.c,e.id);else{a=G(e.c);a.k=e.id;a.t()}})}}};u(e.l);aa(d);e.id!==m?a!==m&&(e.id=m):r(function(){F(k,"focus",x(ja,e),"focusin");F(k,"blur",x(ca,e),"focusout");F(k,"mousemove",x(ka,e));e.o=r(x(ca,e),6E4);F(k,"keydown",
x(ka,e))},500)}};q.TrackEvent=function(a,b){if("string"==typeof b||"number"==typeof b)b={caption:b};b.gs_evt_name=a;R(this,"event",b)};q.Cancel=function(){u(this.N)};h.Tracker=na;h.Cancel=oa;var J=na(n("acct")),q=h.TrackDelay=n("TrackDelay",50);J.N=r(function(){J.TrackView()},q);(function(){var a=l.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){t={H:a,T:c,r:d}});da=!!a})();(q=n("load"))&&q(J);(function(){var a=n("q");if(a)for(var b=0;b<a[s];b+=1)la(J,a[b]);h.q={push:function(a){la(J,a)}}})()})(window.GoSquared||
(GoSquared={}),window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,decodeURIComponent,encodeURIComponent,1,0,null,2147483647,"createElement","split","replace","length","pathname","toLowerCase","cookie","name","hasOwnProperty","removeChild","appendChild","getElementsByTagName","indexOf");
