/*{"version":"6068782","k":"0.16.1","mac":"1:327f78473efa6213933572590566a10f1a5c730dcc2c34f8ee7819ed0285d5ad","created":"2012-07-20T06:54:09Z"}*/
;(function(window,document,undefined){
var g=void 0,k=!0,n=null,o=!1;function p(a){return function(){return this[a]}}var q;function r(a,c,b){var d=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){d.push.apply(d,arguments);return c.apply(a,d)}}function s(a){this.n=a;this.w=g}s.prototype.createElement=function(a,c,b){a=this.n.createElement(a);if(c)for(var d in c)c.hasOwnProperty(d)&&("style"==d?this.pa(a,c[d]):a.setAttribute(d,c[d]));b&&a.appendChild(this.n.createTextNode(b));return a};
function t(a,c,b){a=a.n.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function u(a){function c(){document.body?a():setTimeout(c,0)}c()}function v(a){a.parentNode&&a.parentNode.removeChild(a)}function w(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")}
function x(a,c){for(var b=a.className.split(/\s+/),d=[],e=0,f=b.length;e<f;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function y(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return k;return o}s.prototype.pa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};s.prototype.U=function(){if(this.w===g){var a=this.n.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};
function z(a,c,b,d,e,f,h){this.W=a;this.Pa=c;this.wa=b;this.va=d;this.Ka=e;this.Ja=f;this.ua=h}q=z.prototype;q.getName=p("W");q.getVersion=p("Pa");q.getEngine=p("wa");q.getEngineVersion=p("va");q.getPlatform=p("Ka");q.getPlatformVersion=p("Ja");q.getDocumentMode=p("ua");function A(a,c){this.c=a;this.v=c}var aa=new z("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g);
A.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE"))if(a=B(this.c,/(MSIE [\d\w\.]+)/,1),""!=a){var c=a.split(" ");a=c[0];c=c[1];a=new z(a,c,a,c,C(this),D(this),E(this.v),6<=G(c))}else a=new z("MSIE","Unknown","MSIE","Unknown",C(this),D(this),E(this.v));else if(-1!=this.c.indexOf("Opera"))a:{var c=a="Unknown",b=B(this.c,/(Presto\/[\d\w\.]+)/,1);""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=B(this.c,/rv:([^\)]+)/,1),""!=b&&(c=b));if(-1!=this.c.indexOf("Version/")&&
(b=B(this.c,/Version\/([\d\.]+)/,1),""!=b)){a=new z("Opera",b,a,c,C(this),D(this),E(this.v),10<=G(b));break a}b=B(this.c,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new z("Opera",b,a,c,C(this),D(this),E(this.v),10<=G(b)):new z("Opera","Unknown",a,c,C(this),D(this),E(this.v))}else if(-1!=this.c.indexOf("AppleWebKit")){a=C(this);c=D(this);b=B(this.c,/AppleWebKit\/([\d\.]+)/,1);""==b&&(b="Unknown");var d="Unknown";-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")?d="Chrome":-1!=this.c.indexOf("Safari")?
d="Safari":-1!=this.c.indexOf("AdobeAIR")&&(d="AdobeAIR");var e="Unknown";-1!=this.c.indexOf("Version/")?e=B(this.c,/Version\/([\d\.\w]+)/,1):"Chrome"==d?e=B(this.c,/(Chrome|CrMo)\/([\d\.]+)/,2):"AdobeAIR"==d&&(e=B(this.c,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==d?(B(e,/\d+\.(\d+)/,1),2<G(e)||G(e)):(B(b,/\d+\.(\d+)/,1),526<=G(b)||G(b));a=new z(d,e,"AppleWebKit",b,a,c,E(this.v))}else if(-1!=this.c.indexOf("Gecko")){c=a="Unknown";d=o;-1!=this.c.indexOf("Firefox")?(a="Firefox",b=B(this.c,/Firefox\/([\d\w\.]+)/,
1),""!=b&&(d=B(b,/\d+\.(\d+)/,1),c=b,d=""!=b&&3<=G(b)&&5<=parseInt(d,10))):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla");b=B(this.c,/rv:([^\)]+)/,1);if(""==b)b="Unknown";else if(!d){var d=G(b),e=parseInt(B(b,/\d+\.(\d+)/,1),10),f=parseInt(B(b,/\d+\.\d+\.(\d+)/,1),10);1<d||1==d&&9<e||1==d&&9==e&&2<=f||b.match(/1\.9\.1b[123]/)!=n||b.match(/1\.9\.1\.[\d\.]+/)}a=new z(a,c,"Gecko",b,C(this),D(this),E(this.v))}else a=aa;return a};
function C(a){var c=B(a.c,/(iPod|iPad|iPhone|Android)/,1);if(""!=c)return c;a=B(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}function D(a){var c=B(a.c,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);if(c||(c=B(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;return(a=B(a.c,/Linux ([i\d]+)/,1))?a:"Unknown"}function G(a){a=B(a,/(\d+)/,1);return""!=a?parseInt(a,10):-1}function B(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}
function E(a){if(a.documentMode)return a.documentMode}function da(a,c,b){this.j=a;this.m=c;this.$=b;this.p="wf";this.o=new H("-")}function ea(a){x(a.m,a.o.k(a.p,"loading"));y(a.m,a.o.k(a.p,"active"))||w(a.m,a.o.k(a.p,"inactive"));I(a,"inactive")}function I(a,c,b,d){if(a.$[c])a.$[c](b,d)}function J(a,c,b,d,e){this.j=a;this.B=c;this.D=b;this.u=d;this.H=e;this.O=0;this.qa=this.ia=o}
J.prototype.watch=function(a,c,b,d,e){for(var f=a.length,h=0;h<f;h++){var i=a[h];c[i]||(c[i]=["n4"]);this.O+=c[i].length}e&&(this.ia=e);for(h=0;h<f;h++)for(var i=a[h],e=c[i],j=b[i],l=0,m=e.length;l<m;l++){var ba=e[l],F=this.B,M=i,ca=ba;w(F.m,F.o.k(F.p,M,ca,"loading"));I(F,"fontloading",M,ca);F=r(this,this.xa);M=r(this,this.ya);(new d(F,M,this.j,this.D,this.u,this.H,i,ba,j)).start()}};
J.prototype.xa=function(a,c){var b=this.B;x(b.m,b.o.k(b.p,a,c,"loading"));x(b.m,b.o.k(b.p,a,c,"inactive"));w(b.m,b.o.k(b.p,a,c,"active"));I(b,"fontactive",a,c);this.qa=k;fa(this)};J.prototype.ya=function(a,c){var b=this.B;x(b.m,b.o.k(b.p,a,c,"loading"));y(b.m,b.o.k(b.p,a,c,"active"))||w(b.m,b.o.k(b.p,a,c,"inactive"));I(b,"fontinactive",a,c);fa(this)};
function fa(a){0==--a.O&&a.ia&&(a.qa?(a=a.B,x(a.m,a.o.k(a.p,"loading")),x(a.m,a.o.k(a.p,"inactive")),w(a.m,a.o.k(a.p,"active")),I(a,"active")):ea(a.B))}
function K(a,c,b,d,e,f,h,i,j){this.sa=a;this.Ca=c;this.j=b;this.D=d;this.u=e;this.H=f;this.Ia=new ga;this.Aa=new ha;this.Q=h;this.P=i;this.za=j||"BESbswy";this.ja=ia(this,"arial,'URW Gothic L',sans-serif");this.ka=ia(this,"Georgia,'Century Schoolbook L',serif");this.ga=this.ja;this.ha=this.ka;this.X=L(this,"arial,'URW Gothic L',sans-serif");this.Y=L(this,"Georgia,'Century Schoolbook L',serif")}K.prototype.start=function(){this.Na=this.H();this.aa()};
K.prototype.aa=function(){var a=this.D.T(this.X),c=this.D.T(this.Y);(this.ja!=a||this.ka!=c)&&this.ga==a&&this.ha==c?(a=this.sa,v(this.X),v(this.Y),a(this.Q,this.P)):5E3<=this.H()-this.Na?(a=this.Ca,v(this.X),v(this.Y),a(this.Q,this.P)):(this.ga=a,this.ha=c,ja(this))};function ja(a){a.u(function(a,b){return function(){b.call(a)}}(a,a.aa),25)}function ia(a,c){var b=L(a,c,k),d=a.D.T(b);v(b);return d}function L(a,c,b){c=a.j.createElement("span",{style:ka(a,c,a.P,b)},a.za);t(a.j,"body",c);return c}
function ka(a,c,b,d){b=a.Aa.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(d?"":a.Ia.quote(a.Q)+",")+c+";"+b}function H(a){this.Ga=a||"-"}H.prototype.k=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Ga)};function ga(){this.oa="'"}
ga.prototype.quote=function(a){for(var c=[],a=a.split(/,\s*/),b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");-1==d.indexOf(" ")?c.push(d):c.push(this.oa+d+this.oa)}return c.join(",")};function ha(){this.ma=la;this.F=ma}var la=["font-style","font-weight"],ma={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function na(a,c,b){this.Da=a;this.La=c;this.F=b}na.prototype.expand=function(a,c){for(var b=0;b<this.F.length;b++)if(c==this.F[b][0]){a[this.Da]=this.La+":"+this.F[b][1];break}};ha.prototype.expand=function(a){if(2!=a.length)return n;for(var c=[n,n],b=0,d=this.ma.length;b<d;b++){var e=this.ma[b];(new na(b,e,this.F[e])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":n};function N(a){this.n=a;this.w=g}N.prototype=s.prototype;N.prototype.Ba=function(){return this.n.location.hostname};
function oa(a,c,b){var d=a.n.getElementsByTagName("head")[0];if(d){var e=a.n.createElement("script");e.src=c;var f=o;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=k,b&&b(),e.onload=e.onreadystatechange=n,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e)}}N.prototype.pa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};
N.prototype.U=function(){if(this.w===g){var a=this.n.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};function O(a,c){this.Ma=a;this.ba=c}function pa(a){for(var c=a.Ma.join(","),b=[],d=0;d<a.ba.length;d++){var e=a.ba[d];b.push(e.name+":"+e.value+";")}return c+"{"+b.join("")+"}"}function P(a,c){this.C=a;this.G=c;this.da={};this.ca={}}P.prototype.z=function(a){return a?(this.da[a.I]||this.G).slice(0):this.G.slice(0)};
function qa(a,c,b){for(var d=[],e=a.C.split(",")[0].replace(/"|'/g,""),f=a.z(),h,i=[],j={},l=0;l<f.length;l++)h=f[l],0<h.length&&!j[h]&&(j[h]=k,i.push(h));b=b.na?b.na(e,i,d):i;c=c.I;a.da[c]=b;a.ca[c]=d}P.prototype.watch=function(a,c,b){var d=[],e={};ra(this,c,d,e);a(d,e,b)};function ra(a,c,b,d){b.push(a.C);d[a.C]=a.z(c);a=a.ca[c.I]||[];for(c=0;c<a.length;c++){for(var e=a[c],f=e.C,h=o,i=0;i<b.length;i++)b[i]==f&&(h=k);h||(b.push(f),d[f]=e.z())}}function sa(a,c){this.C=a;this.G=c}sa.prototype.z=p("G");
function ta(a){var c=new Image(1,1);c.src=a;c.onload=function(){c.onload=n}}function Q(a,c){this.I=a;this.fa=c}function R(a){ua.L.push(a)}function va(a){this.j=a;this.r=this.c=this.K=n;this.ta=this.Ea=this.Fa=k;this.l=[];this.A=[];this.ra=this.R=this.M=this.N=n}
function wa(a,c){a.c=c;if(a.K){var b;a:{b=a.K;for(var d=a.c,e=a.Fa,f=a.Ea,h=a.ta,i=0;i<b.L.length;i++){var j=b.L[i];if(j.fa&&j.fa(d.getName(),d.getVersion(),d.getEngine(),d.getEngineVersion(),d.getPlatform(),d.getPlatformVersion(),d.getDocumentMode(),e,f,h)){b=j;break a}}b=n}a.r=b}}q=va.prototype;q.supportsConfiguredBrowser=function(){return!!this.r};
q.init=function(){for(var a=[],c=0;c<this.A.length;c++)a.push(pa(this.A[c]));var c=this.j,a=a.join(""),b=this.j.n.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));t(c,"head",b)};
q.load=function(a,c){var b=this.r.I;if(this.R)for(var d=xa(this.R,b),e=0;e<this.l.length;e++)qa(this.l[e],this.r,d);this.N&&(d=[],this.M&&(d=new ya(this.j,this.r,this.l),d=za(this.M,b,d)),b=this.N.k("https:"==this.j.n.location.protocol,Aa(b,d)),t(this.j,"head",this.j.createElement("link",{rel:"stylesheet",href:b})));a&&u(function(a,b,c,e){return function(){for(var d=0;d<a.l.length;d++)a.l[d].watch(b,c,e&&d==a.l.length-1)}}(this,a,this.r,c))};
q.collectFontFamilies=function(a,c){for(var b=0;b<this.l.length;b++)ra(this.l[b],this.r,a,c)};q.performOptionalActions=function(a){this.V&&u(function(a,b,d,e){return function(){var b=a.V;if(b.la){var h=window.__adobewebfontsappname__,h=h?h.toString().substr(0,20):"";ta(b.la.k("https:"==e.n.location.protocol,{host:encodeURIComponent(e.n.location.hostname),app:encodeURIComponent(h),_:(+new Date).toString()}))}b=a.V;b.Z&&(b=b.Z.k(d,e),t(e,"body",b))}}(this,a,this.c,this.j))};
function S(a,c,b,d){this.Ha=a;this.j=c;this.m=b;this.u=d;this.q=[]}S.prototype.J=function(a){this.q.push(a)};S.prototype.load=function(a,c){var b=a,d=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)d=b||{},b=[];if(b.length)for(var e=this,f=b.length,h=0;h<b.length;h++)Ba(this,b[h],function(){0==--f&&Ca(e,d)});else Ca(this,d)};function Ba(a,c,b){oa(a.j,a.Ha.k("https:"==a.j.n.location.protocol,{id:encodeURIComponent(c)}),b)}
function Ca(a,c){for(var b=new da(a.j,a.m,c),d=o,e=0;e<a.q.length;e++)a.q[e].init(),d=d||a.q[e].supportsConfiguredBrowser();d?(w(b.m,b.o.k(b.p,"loading")),I(b,"loading"),Da(a,b)):ea(b);a.q=[]}function Da(a,c){function b(a,b,c){d.watch(a,b,{},K,c)}for(var d=new J(a.j,c,{T:function(a){return a.offsetWidth}},a.u,function(){return+new Date}),e=0;e<a.q.length;e++){var f=a.q[e];f.supportsConfiguredBrowser()&&(f.load(b,e==a.q.length-1),f.performOptionalActions(window))}}
function T(a,c){this.ea=a;this.u=c;this.q=[]}T.prototype.J=function(a){this.q.push(a)};T.prototype.load=function(){var a=this.ea.__webfonttypekitmodule__;if(a)for(var c=0;c<this.q.length;c++){var b=this.q[c],d=a[b.ra];if(d){var e=this.u;d(function(a,c,d){var c=[],j={};wa(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(n,e),b.collectFontFamilies(c,j),b.performOptionalActions(window));d(b.supportsConfiguredBrowser(),c,j)})}}};function U(a,c){this.W=a;this.na=c}U.prototype.getName=p("W");
function Ea(a){var c=V;Fa(c,a.getName())||c.S.push(a)}function Fa(a,c){for(var b=0;b<a.S.length;b++){var d=a.S[b];if(c===d.getName())return d}return n}function xa(a,c){var b=a.s[c];return b?Fa(a,b):n}function za(a,c,b){for(var d=[],a=a.t[c]||[],c=0;c<a.length;c++){var e;a:switch(a[c]){case "observeddomain":e=new Ga(b.j);break a;case "fontmask":e=new Ha(b.r,b.l);break a;default:e=n}e&&d.push(e)}return d}function ya(a,c,b){this.j=a;this.r=c;this.l=b}function Ga(a){this.j=a}
Ga.prototype.toString=function(){return encodeURIComponent(this.j.Ba?this.j.n.location.hostname:document.location.hostname)};function Ha(a,c){this.r=a;this.l=c}Ha.prototype.toString=function(){for(var a=[],c=0;c<this.l.length;c++)for(var b=this.l[c],d=b.z(),b=b.z(this.r),e=0;e<d.length;e++){var f;a:{for(f=0;f<b.length;f++)if(d[e]===b[f]){f=k;break a}f=o}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(d=a.length;0<d;d-=4)b=a.slice(0>d-4?0:d-4,d),c.unshift(parseInt(b,2).toString(16));return c.join("")};
function W(a){this.Oa=a}W.prototype.k=function(a,c){var b=c||{},d=this.Oa.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,d){return d&&b[c]?"/"+b[c].join("/"):b[c]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function Aa(a,c){for(var b=[],d=0;d<c.length;d++)b.push(c[d].toString());return{format:a,extras:b}}var ua=new function(){this.L=[]};
R(new Q("a",function(a,c,b,d,e,f){if(o||("Windows"==e&&"Unknown"==f?k:o)||("Ubuntu"==e||"Linux"==e?k:o))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=o}else a=o;return a}));
R(new Q("b",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);return!m?o:function(a,b){if("AdobeAIR"==a){var c=/([0-9]+.[0-9]+)/.exec(b);if(c)return 2.5<=parseFloat(c[1])}return o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("a",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);
return!m&&!("Ubuntu"==e||"Linux"==e?k:o)?o:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){var e=parseFloat(c[1]),d=parseInt(c[2],10),c=parseInt(c[3],10);if(!(6<=e)&&(4<e||4==e&&249<d||4==e&&249==d&&4<=c))return k}}return o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("d",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);
return!(m||("Ubuntu"==e||"Linux"==e?k:o)||"CrOS"==e)?o:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return k}}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("a",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,l);return!m&&!("Ubuntu"==e||"Linux"==e?k:o)?o:function(a,b,c,e){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(e)&&!a.test(e)):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("b",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);return!m?o:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("d",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);
return!m&&!("Ubuntu"==e||"Linux"==e?k:o)?o:function(a,b,c,d){return"Gecko"==c&&(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(d))?(a=parseFloat(b[1]),b=parseInt(b[3],10),1.9<a||1.9<=a&&1<b):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("i",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,l);return!m?o:function(a,b,c,d,e,f,h){if("MSIE"==a)return(a=/([0-9]+.[0-9]+)/.exec(b))?6<=parseFloat(a[1])&&(h===g||9>h):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("d",function(a,c,b,d,e,f,h){if(!(c=o))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==e&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=o;a=c||("Windows"==e&&"6.0"==f?k:o)?"MSIE"==a?9<=h:g:o;return a}));
R(new Q("a",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,l);return!m&&!("Ubuntu"==e||"Linux"==e?k:o)?o:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("b",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);return!m?o:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("d",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);
return!m&&!("Ubuntu"==e||"Linux"==e?k:o)?o:"Opera"==a?11.1<=parseFloat(c):o}));R(new Q("b",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);return!m?o:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("a",function(a,c,b,d,e,f,h,i,j,l){var m;m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,d,e,f,h,i,j,l);return!m?o:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("d",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||("Windows"==e&&"5.1"==f?k:o)||("Windows"==e&&"5.2"==f?k:o)||("Windows"==e&&"6.0"==f?k:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:o}(a,c,b,d,e,f,h,i,j,l);
return!m?o:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?534.5<=parseFloat(a[1]):o}(a,c,b,d,e,f,h,i,j,l)}));
R(new Q("a",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||function(a,b,c,d,e,f,h,i,j){return j&&"iPad"==e&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,d,e,f,h,i){if(i&&("iPhone"==e||"iPod"==e))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b;return o}(a,c,b,d,e,f,h,i,j,l);return!m?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?k:o}));
R(new Q("d",function(a,c,b,d,e,f,h,i,j,l){var m;m=(m=o||function(a,b,c,d,e,f,h,i,j){return j&&"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):o:o}(a,c,b,d,e,f,h,i,j,l))||function(a,b,c,d,e,f,h,i){return i&&("iPhone"==e||"iPod"==e)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):o:o}(a,c,b,d,e,f,h,i,j,l);return!m?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?k:o}));var V=new function(){this.S=[];this.s={}};
Ea(new U("AllFonts",function(a,c){return c}));
Ea(new U("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var d=0;d<c.length;d++){var e=c[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;b.push(new sa(f,[e]))}a={};for(e=0;e<c.length;e++)b=c[e],d=b.charAt(1),(a[d]||(a[d]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<b.length;e++)for(var f=b[e],h=0;h<f.length;h++){var i=f[h];if(a[i]){d=d.concat(a[i]);break}}b=d;d={};a=[];for(e=0;e<b.length;e++)f=b[e],d[f]||(d[f]=k,a.push(f));b=[];for(d=0;d<c.length;d++){e=c[d];
for(f=0;f<a.length;f++)h=a[f],h==e&&b.push(h)}return b}));V.s.a="AllFonts";V.s.b="AllFonts";V.s.d="AllFonts";V.s.e="AllFonts";V.s.f="AllFonts";V.s.g="AllFonts";V.s.h="AllFonts";V.s.i="DefaultFourFontsWithSingleFvdFamilies";var X=new function(){this.t={}};X.t.a=[];X.t.b=[];X.t.d=[];X.t.e=[];X.t.f=["observeddomain"];X.t.g=["observeddomain"];X.t.h=["observeddomain"];X.t.i=["observeddomain","fontmask"];window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ia=function(a,c){setTimeout(a,c)},Y=new S(new W("//use.typekit.net/{id}.js"),new N(document),document.documentElement,Ia),Z=new T(window,Ia);window.Typekit.load=function(){Y.load.apply(Y,arguments)};window.Typekit.addKit=function(){Y.J.apply(Y,arguments)}}var Ja,$;Ja=new function(){this.la=this.Z=n};$=new va(new N(document));$.ra="uqi6bct";$.N=new W("//use.typekit.net/k/uqi6bct-{format}.css?3bb2a6e53c9684ffdc9a9bff1b5b2a629811bf9003a7728c0cd239af52fb5cc378f872d944c9ed84a168c8dc52f3288532a62370812a4f176dac38f5501cebba48fcd628b6d1189f81d22416fd723b2a1adbd0a85e3f36523216e2dc7331f73af2752041bc0d51e5a353bd9aa9063f61623ca3b9a9131cbdd87daf541284540aff8715c6c163a360964a14e51e31a6907dcd8b53df4ba3d1e4f2210d7592cb8ceb45d8180f5f26f427e0bcb09008720dde823a5828f94bf4026694ef640e65");
$.V=Ja;$.l.push(new P("proxima-nova-1,proxima-nova-2",["n4","i4","n7","i7"]));$.l.push(new P("proxima-nova-condensed-1,proxima-nova-condensed-2",["n6"]));$.l.push(new P("athelas-1,athelas-2",["n4"]));$.A.push(new O([".title","body section"],[{name:"font-family",value:'"proxima-nova-1","proxima-nova-2","Helmet","Freesans",sans-serif'}]));$.A.push(new O([".subtitle"],[{name:"font-family",value:'"proxima-nova-condensed-1","proxima-nova-condensed-2","Helmet","Freesans",sans-serif'}]));
$.A.push(new O([".heading","h2"],[{name:"font-family",value:'"athelas-1","athelas-2","Baskerville","Georgia",serif'}]));$.K=ua;$.M=X;$.R=V;Z&&Z.ea.__webfonttypekitmodule__?(Z.J($),Z.load()):(wa($,(new A(navigator.userAgent,document)).parse()),window.Typekit.addKit($));
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=uqi6bct&ht=tk&h={host}&f=176.140.175.139.149.1692&a=957&_={_}"};
/*{"created":"2012-12-13T00:36:36Z","k":"1.2.0"}*/
;(function(window,document,undefined){
function e(b,a){this.b=a||b;this.a=document}e.prototype=function(b,a){this.b=a||b;this.a=this.b.document}.prototype;function f(b){var a=new Image(1,1);a.src=b;a.onload=function(){a.onload=null}}function g(){this.d=window.Typekit.config.p}function h(b,a,c){var d=c||{},b=b.d.replace(/\{\/?([^*}]*)(\*?)\}/g,function(b,a,c){return c&&d[a]?"/"+d[a].join("/"):d[a]||""});b.match(/^\/\//)&&(b=(a?"https:":"http:")+b);return b.replace(/\/*\?*($|\?)/,"$1")}window.Typekit||(window.Typekit={});
var i=new e(window),j=new function(){this.c=new g},k=!1;function l(){if(!k)for(var b=document.getElementsByTagName("link"),a=0;a<b.length;a++){var c=b[a].getAttribute("href");if(c&&0<=c.indexOf("use.typekit")){b=j;a=i;b.c&&(c=(c=window.__adobewebfontsappname__)?c.toString().substr(0,20):"",f(h(b.c,"https:"==a.a.location.protocol,{host:encodeURIComponent(a.a.location.hostname),app:encodeURIComponent(c),_:(+new Date).toString()})));k=!0;break}}}var m=window.Typekit.load;
window.Typekit.load=function(){m&&m.apply(window.Typekit,arguments);l()};window.__webfonttypekitmodule__&&l();
})(this,document);
